version: '3'

services:
  user-db: 
    image: postgres:16-alpine
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      SECRET_KEY: fahmi

  user-service:
    build: ./user-service
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - user-db
      - book-service
    environment:
      - PORT=8080
      - DB_URL=postgresql://postgres:postgres@user-db:5432/user-db
      
  book-service:
    build: ./book-service
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    