version: '3'

services:
  book-service:
    build: .
    ports:
      - '3000:3000' 
    restart: always
    depends_on:
      - nodejs-db
    environment:
      - PORT=3000
      - DB_URL=postgresql://postgres:postgres@nodejs-db:5432/nodejs-db  
      - SECRET_KEY=fahmi

  nodejs-db: 
    image: postgres:16-alpine
    ports:
      - 5435:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
