apiVersion: v1
kind: Service
metadata:
  name: book-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: book-db

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-db
  template:
    metadata:
      labels:
        app: book-db
    spec:
      containers:
        - name: book-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "book-db"
