version: '3'

services:
  db: 
    image: postgres:16-alpine
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      SECRET_KEY: fahmi

  api:
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
    environment:
      - PORT=8080
      - DB_URL=postgresql://user:password@db:5432/library?sslmode=disable
