name: Lint and Trigger Jenkins

on:
  pull_request:
    types: [closed]

jobs:
  unit-test-and-lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./book-service/package-lock.json

    - name: Setup and run tests
      working-directory: ./book-service
      run: |
        npm ci
        npm run build --if-present
        npm test

    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: "main"
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

  # trigger-jenkins-job:
  #   name: Trigger Jenkins Job
  #   runs-on: ubuntu-latest
  #   if: github.event.pull_request.merged == true

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Trigger Jenkins Job
  #       env:
  #         JENKINS_TOKEN: ${{ secrets.JEKINS_TOKEN }}
  #       run: |
  #         curl -X POST "http://ec2-54-91-214-106.compute-1.amazonaws.com:8080/job/first-job/build?token=${JENKINS_TOKEN}" --user admin:${JENKINS_TOKEN}
